version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-pricing
    ports:
      - "${REDIS_HOST:-127.0.0.1}:${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 30s
      retries: 10

volumes:
  redis_data: